-- Trainfitter — sh_lang.lua
-- Made by SellingVika.

Trainfitter      = Trainfitter or {}
Trainfitter.Lang = Trainfitter.Lang or {}

Trainfitter.SupportedLanguages = { "en", "ru", "da" }

Trainfitter.Lang.en = {
    code               = "en",
    label              = "English",
    brand              = "Trainfitter",
    refused_mount      = "Refused to mount %s: %s",
    added_downloading  = "%s added: %s — downloading…",
    server_added_dl    = "Server added: %s — downloading…",
    ready              = "Ready: %s",
    download_error     = "Download error %s: %s",
    skin_removed       = "Skin %s removed.",
    server_installed   = "%s installed '%s' (%.1f MB)",
    apply_hint         = "To apply: gmod_train_spawner → pick skin/mask → aim at train → press R.",
    no_perm_download   = "Not enough permissions to download.",
    no_perm_persistent = "Only admins can mark addon as persistent.",
    no_perm_delete     = "No permission to delete skins.",
    no_perm_settings   = "No permission to change settings.",
    too_often          = "Too often. Wait a bit.",
    invalid_wsid       = "Invalid WSID.",
    not_found          = "Addon %s not found in Workshop.",
    not_gmod_addon     = "'%s' is not a Garry's Mod addon (appid %s). Denied.",
    too_big            = "'%s' weighs %.1f MB, limit %d MB. Denied.",
    validating         = "Validating '%s' on server (%.1f MB)…",
    install_failed     = "Failed to install '%s': %s",
    saved_active       = "'%s' saved as active skin.",
    deleted_for_all    = "Skin %s removed for all players.",
    nav_install        = "Install",
    nav_favorites      = "Favorites",
    nav_history        = "History",
    nav_settings       = "Settings",
    install_title      = "Install skin",
    favorites_title    = "Favorites",
    history_title      = "History",
    settings_title     = "Server settings",
    address_placeholder= "Paste a Workshop link or WSID…",
    open_workshop      = "Open Workshop",
    confirm            = "Confirm",
    apply              = "Apply",
    remove             = "Remove",
    open_browser       = "Open in browser",
    refresh            = "Refresh",
    make_persistent    = "Make persistent",
    add_to_favorites   = "Add to favorites",
    in_favorites       = "In favorites",
    delete_history     = "Delete from history",
    clear_history      = "Clear history",
    clear_history_confirm = "Clear the entire history (%d entries)?",
    history_cleared    = "History cleared.",
    no_perm_chat       = "%s tried to change Trainfitter setting but lacks permission.",
    settings_changed_chat = "[Trainfitter] %s changed %s = %s",
    select_addon_above = "Pick an addon above",
    paste_and_enter    = "Paste a link and press Enter.",
    selected           = "Selected: %s",
    need_url_or_wsid   = "Need a steamcommunity.com link or numeric WSID.",
    request_sent       = "Request sent.",
    saving_persistent  = "Saving %s as persistent…",
    removed_persistent = "%s removed from persistent.",
    loading_preview    = "Loading preview…",
    no_data            = "No data",
    no_preview         = "No preview",
    no_title           = "(no title)",
    not_downloaded_yet = "(not downloaded yet)",
    history_hint       = "Recent downloads from this session. Click Apply to make a skin active.",
    history_empty      = "History is empty. Download something on the Install tab.",
    settings_hint      = "Changes apply instantly and are written to audit.log.",
    settings_loading   = "Loading settings…",
    settings_no_perm   = "You don't have permission to change settings.",
    active_skins       = "Active skins (%d)",
    no_active_skins    = "No downloaded skins in this session yet.",
    delete_confirm     = "Remove skin %s for ALL server players?\nLocal cached files will also be cleared (via Unsubscribe).",
    delete_title       = "Delete skin",
    cancel             = "Cancel",
    active_label       = "Active: %s",
    no_active_label    = "No active skin",
    chip_active        = "Active",
    chip_persistent    = "Persistent",
    chip_downloaded    = "Downloaded",
    chip_mounted       = "Mounted",
    history_ok         = "Downloaded",
    history_err        = "Error",
    language           = "Language",
}

Trainfitter.Lang.ru = {
    code               = "ru",
    label              = "Русский",
    brand              = "Trainfitter",
    refused_mount      = "Не удалось смонтировать %s: %s",
    added_downloading  = "%s добавил: %s — скачиваю…",
    server_added_dl    = "Сервер добавил: %s — скачиваю…",
    ready              = "Готово: %s",
    download_error     = "Ошибка загрузки %s: %s",
    skin_removed       = "Скин %s удалён.",
    server_installed   = "%s установил '%s' (%.1f МБ)",
    apply_hint         = "Применение: gmod_train_spawner → выбери скин/маску → наведись на состав → R.",
    no_perm_download   = "Недостаточно прав для скачивания.",
    no_perm_persistent = "Только админы могут отметить аддон как постоянный.",
    no_perm_delete     = "Нет прав на удаление скинов.",
    no_perm_settings   = "Нет прав на изменение настроек.",
    too_often          = "Слишком часто. Подожди немного.",
    invalid_wsid       = "Некорректный WSID.",
    not_found          = "Аддон %s не найден в Мастерской.",
    not_gmod_addon     = "'%s' не аддон Garry's Mod (appid %s). Отказано.",
    too_big            = "'%s' весит %.1f МБ, лимит %d МБ. Отказано.",
    validating         = "Проверяю '%s' на сервере (%.1f МБ)…",
    install_failed     = "Не удалось установить '%s': %s",
    saved_active       = "'%s' сохранён как активный скин.",
    deleted_for_all    = "Скин %s удалён у всех игроков.",
    nav_install        = "Установка",
    nav_favorites      = "Избранное",
    nav_history        = "История",
    nav_settings       = "Настройки",
    install_title      = "Установка скина",
    favorites_title    = "Избранное",
    history_title      = "История",
    settings_title     = "Настройки сервера",
    address_placeholder= "Вставь ссылку на аддон или WSID…",
    open_workshop      = "Открыть Мастерскую",
    confirm            = "Подтвердить",
    apply              = "Применить",
    remove             = "Убрать",
    open_browser       = "В браузере",
    refresh            = "Обновить",
    make_persistent    = "Сделать постоянным",
    add_to_favorites   = "В избранное",
    in_favorites       = "В избранном",
    delete_history     = "Убрать из истории",
    clear_history      = "Очистить историю",
    clear_history_confirm = "Очистить всю историю (%d записей)?",
    history_cleared    = "История очищена.",
    no_perm_chat       = "%s пытается менять настройку Trainfitter без прав.",
    settings_changed_chat = "[Trainfitter] %s изменил %s = %s",
    select_addon_above = "Выбери аддон сверху",
    paste_and_enter    = "Вставь ссылку и нажми Enter.",
    selected           = "Выбрано: %s",
    need_url_or_wsid   = "Нужна ссылка steamcommunity.com или числовой WSID.",
    request_sent       = "Запрос отправлен.",
    saving_persistent  = "Сохраняю %s как постоянный…",
    removed_persistent = "%s убран из постоянных.",
    loading_preview    = "Загружаю превью…",
    no_data            = "Нет данных",
    no_preview         = "Нет превью",
    no_title           = "(без названия)",
    not_downloaded_yet = "(ещё не скачан)",
    history_hint       = "Последние скачки этой сессии. «Применить» — сделать скин активным.",
    history_empty      = "История пуста. Скачай что-нибудь во вкладке Установка.",
    settings_hint      = "Изменения применяются мгновенно и пишутся в audit.log.",
    settings_loading   = "Загружаю настройки…",
    settings_no_perm   = "У тебя нет прав менять настройки.",
    active_skins       = "Активные скины (%d)",
    no_active_skins    = "Пока нет скачанных скинов в этой сессии.",
    delete_confirm     = "Удалить скин %s у ВСЕХ игроков сервера?\nЛокальные файлы тоже попытаются очиститься (через Unsubscribe).",
    delete_title       = "Удаление скина",
    cancel             = "Отмена",
    active_label       = "Активный: %s",
    no_active_label    = "Активный скин: нет",
    chip_active        = "Активный",
    chip_persistent    = "Избранное",
    chip_downloaded    = "Скачан",
    chip_mounted       = "Смонтирован",
    history_ok         = "Скачан",
    history_err        = "Ошибка",
    language           = "Язык",
}

Trainfitter.Lang.da = {
    code               = "da",
    label              = "Dansk",
    brand              = "Trainfitter",
    refused_mount      = "Kunne ikke montere %s: %s",
    added_downloading  = "%s tilføjede: %s — downloader…",
    server_added_dl    = "Serveren tilføjede: %s — downloader…",
    ready              = "Klar: %s",
    download_error     = "Downloadfejl %s: %s",
    skin_removed       = "Skin %s er fjernet.",
    server_installed   = "%s installerede '%s' (%.1f MB)",
    apply_hint         = "Brug: gmod_train_spawner → vælg skin/maske → sigt på toget → tryk R.",
    no_perm_download   = "Ikke tilstrækkelige rettigheder til at downloade.",
    no_perm_persistent = "Kun administratorer kan markere et addon som permanent.",
    no_perm_delete     = "Ingen rettigheder til at slette skins.",
    no_perm_settings   = "Ingen rettigheder til at ændre indstillinger.",
    too_often          = "For ofte. Vent et øjeblik.",
    invalid_wsid       = "Ugyldigt WSID.",
    not_found          = "Addonet %s blev ikke fundet i Workshop.",
    not_gmod_addon     = "'%s' er ikke et Garry's Mod-addon (appid %s). Afvist.",
    too_big            = "'%s' fylder %.1f MB, grænsen er %d MB. Afvist.",
    validating         = "Validerer '%s' på serveren (%.1f MB)…",
    install_failed     = "Kunne ikke installere '%s': %s",
    saved_active       = "'%s' gemt som aktivt skin.",
    deleted_for_all    = "Skin %s er fjernet for alle spillere.",
    nav_install        = "Installer",
    nav_favorites      = "Favoritter",
    nav_history        = "Historik",
    nav_settings       = "Indstillinger",
    install_title      = "Installer skin",
    favorites_title    = "Favoritter",
    history_title      = "Historik",
    settings_title     = "Serverindstillinger",
    address_placeholder= "Indsæt et Workshop-link eller WSID…",
    open_workshop      = "Åbn Workshop",
    confirm            = "Bekræft",
    apply              = "Anvend",
    remove             = "Fjern",
    open_browser       = "Åbn i browser",
    refresh            = "Opdater",
    make_persistent    = "Gør permanent",
    add_to_favorites   = "Tilføj til favoritter",
    in_favorites       = "I favoritter",
    delete_history     = "Fjern fra historik",
    clear_history      = "Ryd historik",
    clear_history_confirm = "Rydde hele historikken (%d poster)?",
    history_cleared    = "Historik ryddet.",
    no_perm_chat       = "%s forsøgte at ændre Trainfitter-indstilling uden rettigheder.",
    settings_changed_chat = "[Trainfitter] %s ændrede %s = %s",
    select_addon_above = "Vælg et addon ovenfor",
    paste_and_enter    = "Indsæt et link og tryk Enter.",
    selected           = "Valgt: %s",
    need_url_or_wsid   = "Skal være et steamcommunity.com-link eller numerisk WSID.",
    request_sent       = "Anmodning sendt.",
    saving_persistent  = "Gemmer %s som permanent…",
    removed_persistent = "%s fjernet fra permanente.",
    loading_preview    = "Henter forhåndsvisning…",
    no_data            = "Ingen data",
    no_preview         = "Ingen forhåndsvisning",
    no_title           = "(uden titel)",
    not_downloaded_yet = "(ikke hentet endnu)",
    history_hint       = "Seneste downloads i denne session. Tryk Anvend for at aktivere et skin.",
    history_empty      = "Historikken er tom. Hent noget under Installer-fanen.",
    settings_hint      = "Ændringer træder i kraft straks og skrives til audit.log.",
    settings_loading   = "Henter indstillinger…",
    settings_no_perm   = "Du har ikke rettigheder til at ændre indstillinger.",
    active_skins       = "Aktive skins (%d)",
    no_active_skins    = "Ingen hentede skins i denne session endnu.",
    delete_confirm     = "Fjern skin %s for ALLE spillere på serveren?\nLokale filer forsøges også ryddet (via Unsubscribe).",
    delete_title       = "Slet skin",
    cancel             = "Annuller",
    active_label       = "Aktiv: %s",
    no_active_label    = "Intet aktivt skin",
    chip_active        = "Aktiv",
    chip_persistent    = "Permanent",
    chip_downloaded    = "Hentet",
    chip_mounted       = "Monteret",
    history_ok         = "Hentet",
    history_err        = "Fejl",
    language           = "Sprog",
}

if CLIENT then
    CreateClientConVar("trainfitter_lang", "ru", true, false,
        "Trainfitter UI language: en, ru, da.")
end

function Trainfitter.GetLang()
    if CLIENT then
        local cv = GetConVar("trainfitter_lang")
        local v = cv and string.lower(cv:GetString() or "ru") or "ru"
        if not Trainfitter.Lang[v] then v = "ru" end
        return v
    end
    return "ru"
end

function Trainfitter.L(key, ...)
    local code = Trainfitter.GetLang()
    local tbl  = Trainfitter.Lang[code] or Trainfitter.Lang.ru
    local raw  = tbl[key] or Trainfitter.Lang.en[key] or key
    if select("#", ...) > 0 then
        local ok, formatted = pcall(string.format, raw, ...)
        if ok then return formatted end
        return raw
    end
    return raw
end
