-- Trainfitter - sh_lang.lua
-- Made by SellingVika

Trainfitter      = Trainfitter or {}
Trainfitter.Lang = Trainfitter.Lang or {}

Trainfitter.SupportedLanguages = { "en", "ru", "da" }

Trainfitter.Lang.en = {
    code               = "en",
    label              = "English",
    brand              = "Trainfitter",
    refused_mount      = "Bounced %s: %s",
    added_downloading  = "%s queued %s - downloading",
    server_added_dl    = "Server queued %s - downloading",
    ready              = "Ready: %s",
    download_error     = "%s download died: %s",
    skin_removed       = "Skin %s gone",
    server_installed   = "%s installed '%s' (%.1f MB)",
    apply_hint         = "Apply: gmod_train_spawner -> pick skin/mask -> aim at train -> press R",
    no_perm_download   = "Not enough perms to download, sorry kid",
    no_perm_persistent = "Only admins mark addons as persistent",
    no_perm_delete     = "No perms to nuke skins",
    no_perm_settings   = "Settings are not for you",
    too_often          = "Slow down, take a breath",
    invalid_wsid       = "WSID is bogus",
    not_found          = "Addon %s nowhere in Workshop - deleted maybe, or you fat-fingered",
    not_gmod_addon     = "'%s' is not a gmod addon (appid %s), nope",
    too_big            = "'%s' weighs %.1f MB at a %d MB cap, denied",
    validating         = "X-raying '%s' on server (%.1f MB)",
    install_failed     = "'%s' didn't make it: %s",
    saved_active       = "'%s' is live, enjoy",
    deleted_for_all    = "Skin %s wiped for everyone",
    nav_install        = "Install",
    nav_favorites      = "Favorites",
    nav_history        = "History",
    nav_settings       = "Settings",
    install_title      = "Install skin",
    favorites_title    = "Favorites",
    history_title      = "History",
    settings_title     = "Server settings",
    address_placeholder= "Paste a Workshop link or WSID",
    open_workshop      = "Open Workshop",
    confirm            = "Confirm",
    apply              = "Apply",
    remove             = "Remove",
    open_browser       = "Open in browser",
    refresh            = "Refresh",
    make_persistent    = "Make persistent",
    add_to_favorites   = "Add to favorites",
    in_favorites       = "In favorites",
    delete_history     = "Delete from history",
    clear_history      = "Clear history",
    clear_history_confirm = "Wipe the whole history (%d entries) ?",
    history_cleared    = "History wiped",
    no_perm_chat       = "%s tried to flip a Trainfitter setting but lacks perms",
    settings_changed_chat = "[Trainfitter] %s changed %s = %s",
    purge_client          = "Purge my cache",
    purge_client_done     = "Local cache purged: %d previews, %d cached GMAs",
    remove_active_tooltip = "Remove active skin",
    close_menu_tooltip    = "Close menu",
    remove_active_confirm = "Remove active skin '%s' for EVERYONE on the server ?",
    remove_active_title   = "Remove active skin",
    select_addon_above = "Pick an addon above",
    paste_and_enter    = "Paste a link, hit Enter",
    selected           = "Picked: %s",
    need_url_or_wsid   = "Need a steamcommunity.com link or numeric WSID, not whatever this is",
    request_sent       = "Request sent, sit tight",
    saving_persistent  = "Saving %s as persistent",
    removed_persistent = "%s yanked from persistent",
    loading_preview    = "Fetching preview",
    no_data            = "No data",
    no_preview         = "No preview",
    no_title           = "(no title)",
    not_downloaded_yet = "(not downloaded yet)",
    history_hint       = "Your recent downloads this session. Apply makes a skin active",
    history_empty      = "History is empty, grab something on the Install tab",
    settings_hint      = "Changes apply instantly and go straight to audit.log",
    settings_loading   = "Loading settings",
    settings_no_perm   = "You don't have permission to touch settings",
    active_skins       = "Active skins (%d)",
    no_active_skins    = "Nothing downloaded this session yet",
    delete_confirm     = "Remove skin %s for EVERYONE on the server ?\nLocal cache will also go (via Unsubscribe)",
    delete_title       = "Delete skin",
    cancel             = "Cancel",
    active_label       = "Active: %s",
    no_active_label    = "No active skin",
    chip_active        = "Active",
    chip_persistent    = "Persistent",
    chip_downloaded    = "Downloaded",
    chip_mounted       = "Mounted",
    history_ok         = "Downloaded",
    history_err        = "Failed",
    language           = "Language",
    col_title          = "Title",
    col_size           = "Size",
}

Trainfitter.Lang.ru = {
    code               = "ru",
    label              = "Русский",
    brand              = "Trainfitter",
    refused_mount      = "Не пустили %s, причина: %s",
    added_downloading  = "%s закинул %s, качаю не нервничай",
    server_added_dl    = "Сервер сам подсунул %s, качаю",
    ready              = "Готово, %s на месте",
    download_error     = "Скачка %s гавкнула: %s",
    skin_removed       = "Скин %s в небытие",
    server_installed   = "%s поставил '%s' (%.1f МБ)",
    apply_hint         = "Применить: gmod_train_spawner -> выбрал скин/маску -> навёлся на поезд -> R и поехали",
    no_perm_download   = "Прав маловато чтобы качать, сорян",
    no_perm_persistent = "Постоянным может только админ, не ты",
    no_perm_delete     = "Удалять скины - не для тебя",
    no_perm_settings   = "Настройки крутить не разрешено, ты не админ",
    too_often          = "Куда так шустро, притормози",
    invalid_wsid       = "WSID кривой, перепроверь циферки",
    not_found          = "Аддона %s в Мастерской нет - удалили или ты ошибся в цифрах",
    not_gmod_addon     = "'%s' - это не gmod-аддон (appid %s), мимо кассы",
    too_big            = "'%s' жирный, %.1f МБ при лимите %d МБ, не лезет",
    validating         = "Просвечиваю '%s' рентгеном (%.1f МБ)",
    install_failed     = "Не выгорело с '%s': %s",
    saved_active       = "'%s' активен, наслаждайся",
    deleted_for_all    = "Скин %s снесли у всех",
    nav_install        = "Установка",
    nav_favorites      = "Избранное",
    nav_history        = "История",
    nav_settings       = "Настройки",
    install_title      = "Установка скина",
    favorites_title    = "Избранное",
    history_title      = "История",
    settings_title     = "Настройки сервера",
    address_placeholder= "Вкинь ссылку или WSID",
    open_workshop      = "Открыть Мастерскую",
    confirm            = "Подтвердить",
    apply              = "Применить",
    remove             = "Убрать",
    open_browser       = "В браузере",
    refresh            = "Обновить",
    make_persistent    = "Сделать постоянным",
    add_to_favorites   = "В избранное",
    in_favorites       = "В избранном",
    delete_history     = "Убрать из истории",
    clear_history      = "Очистить историю",
    clear_history_confirm = "Снести всю историю (%d записей) ?",
    history_cleared    = "Историю снесло",
    no_perm_chat       = "%s пытается крутить настройку Trainfitter без прав, ну дурак же",
    settings_changed_chat = "[Trainfitter] %s изменил %s = %s",
    purge_client          = "Очистить мой кеш",
    purge_client_done     = "Локальный кеш очищен: %d превью, %d кешированных GMA",
    remove_active_tooltip = "Убрать активный скин",
    close_menu_tooltip    = "Закрыть меню",
    remove_active_confirm = "Убрать активный скин '%s' у ВСЕХ игроков сервера ?",
    remove_active_title   = "Убрать активный скин",
    select_addon_above = "Выбери аддон сверху",
    paste_and_enter    = "Вкинь ссылку, нажми Enter",
    selected           = "Выбран: %s",
    need_url_or_wsid   = "Тут нужна ссылка steamcommunity.com либо WSID цифрами, а не вот это вот",
    request_sent       = "Запрос ушёл, ждём",
    saving_persistent  = "Сохраняю %s как постоянный",
    removed_persistent = "%s выкинут из постоянных",
    loading_preview    = "Тяну превью",
    no_data            = "Нет данных",
    no_preview         = "Нет превью",
    no_title           = "(без названия)",
    not_downloaded_yet = "(ещё не скачан)",
    history_hint       = "Последние скачки этой сессии, «Применить» делает скин активным",
    history_empty      = "История пустая, иди во вкладку Установка и скачай что-нибудь",
    settings_hint      = "Что крутишь - сразу применяется и пишется в audit.log, всё видно",
    settings_loading   = "Тяну настройки",
    settings_no_perm   = "Прав менять настройки у тебя нет",
    active_skins       = "Активные скины (%d)",
    no_active_skins    = "В этой сессии пока ничего не скачано",
    delete_confirm     = "Снести скин %s у ВСЕХ игроков сервера ?\nЛокальный кеш тоже отлетит (через Unsubscribe)",
    delete_title       = "Удаление скина",
    cancel             = "Отмена",
    active_label       = "Активный: %s",
    no_active_label    = "Активного скина нет",
    chip_active        = "Активный",
    chip_persistent    = "Избранное",
    chip_downloaded    = "Скачан",
    chip_mounted       = "Смонтирован",
    history_ok         = "Скачан",
    history_err        = "Ошибка",
    language           = "Язык",
    col_title          = "Название",
    col_size           = "Размер",
}

Trainfitter.Lang.da = {
    code               = "da",
    label              = "Dansk",
    brand              = "Trainfitter",
    refused_mount      = "Afvist %s: %s",
    added_downloading  = "%s tilføjede %s - downloader",
    server_added_dl    = "Serveren tilføjede %s - downloader",
    ready              = "Klar: %s",
    download_error     = "Downloadfejl %s: %s",
    skin_removed       = "Skin %s er væk",
    server_installed   = "%s installerede '%s' (%.1f MB)",
    apply_hint         = "Brug: gmod_train_spawner -> vælg skin/maske -> sigt på toget -> tryk R",
    no_perm_download   = "Ikke nok rettigheder til at downloade",
    no_perm_persistent = "Kun administratorer kan markere som permanent",
    no_perm_delete     = "Ingen rettigheder til at slette skins",
    no_perm_settings   = "Ingen rettigheder til indstillinger",
    too_often          = "For ofte, vent lidt",
    invalid_wsid       = "Ugyldigt WSID",
    not_found          = "Addonet %s ikke fundet i Workshop",
    not_gmod_addon     = "'%s' er ikke et Garry's Mod-addon (appid %s), afvist",
    too_big            = "'%s' fylder %.1f MB ved en %d MB grænse, afvist",
    validating         = "Validerer '%s' på serveren (%.1f MB)",
    install_failed     = "'%s' lykkedes ikke: %s",
    saved_active       = "'%s' gemt som aktivt skin",
    deleted_for_all    = "Skin %s fjernet for alle spillere",
    nav_install        = "Installer",
    nav_favorites      = "Favoritter",
    nav_history        = "Historik",
    nav_settings       = "Indstillinger",
    install_title      = "Installer skin",
    favorites_title    = "Favoritter",
    history_title      = "Historik",
    settings_title     = "Serverindstillinger",
    address_placeholder= "Indsæt et Workshop-link eller WSID",
    open_workshop      = "Åbn Workshop",
    confirm            = "Bekræft",
    apply              = "Anvend",
    remove             = "Fjern",
    open_browser       = "Åbn i browser",
    refresh            = "Opdater",
    make_persistent    = "Gør permanent",
    add_to_favorites   = "Tilføj til favoritter",
    in_favorites       = "I favoritter",
    delete_history     = "Fjern fra historik",
    clear_history      = "Ryd historik",
    clear_history_confirm = "Ryd hele historikken (%d poster) ?",
    history_cleared    = "Historik ryddet",
    no_perm_chat       = "%s prøvede at ændre en Trainfitter-indstilling uden rettigheder",
    settings_changed_chat = "[Trainfitter] %s ændrede %s = %s",
    purge_client          = "Ryd min cache",
    purge_client_done     = "Lokal cache ryddet: %d previews, %d cachede GMAer",
    remove_active_tooltip = "Fjern aktivt skin",
    close_menu_tooltip    = "Luk menu",
    remove_active_confirm = "Fjern aktivt skin '%s' for ALLE spillere på serveren ?",
    remove_active_title   = "Fjern aktivt skin",
    select_addon_above = "Vælg et addon ovenfor",
    paste_and_enter    = "Indsæt et link, tryk Enter",
    selected           = "Valgt: %s",
    need_url_or_wsid   = "Skal være et steamcommunity.com-link eller numerisk WSID",
    request_sent       = "Anmodning sendt",
    saving_persistent  = "Gemmer %s som permanent",
    removed_persistent = "%s fjernet fra permanente",
    loading_preview    = "Henter forhåndsvisning",
    no_data            = "Ingen data",
    no_preview         = "Ingen forhåndsvisning",
    no_title           = "(uden titel)",
    not_downloaded_yet = "(ikke hentet endnu)",
    history_hint       = "Seneste downloads i denne session, tryk Anvend for at aktivere et skin",
    history_empty      = "Historikken er tom, hent noget under Installer-fanen",
    settings_hint      = "Ændringer træder i kraft straks og skrives til audit.log",
    settings_loading   = "Henter indstillinger",
    settings_no_perm   = "Du har ikke rettigheder til indstillinger",
    active_skins       = "Aktive skins (%d)",
    no_active_skins    = "Ingen hentede skins i denne session endnu",
    delete_confirm     = "Fjern skin %s for ALLE spillere på serveren ?\nLokal cache forsøges også ryddet (via Unsubscribe)",
    delete_title       = "Slet skin",
    cancel             = "Annuller",
    active_label       = "Aktiv: %s",
    no_active_label    = "Intet aktivt skin",
    chip_active        = "Aktiv",
    chip_persistent    = "Permanent",
    chip_downloaded    = "Hentet",
    chip_mounted       = "Monteret",
    history_ok         = "Hentet",
    history_err        = "Fejl",
    language           = "Sprog",
    col_title          = "Titel",
    col_size           = "Størrelse",
}

if CLIENT then
    CreateClientConVar("trainfitter_lang", "ru", true, false,
        "Trainfitter UI language: en, ru, da.")
end

function Trainfitter.GetLang()
    if CLIENT then
        local cv = GetConVar("trainfitter_lang")
        local v = cv and string.lower(cv:GetString() or "ru") or "ru"
        if not Trainfitter.Lang[v] then v = "ru" end
        return v
    end
    return "ru"
end

function Trainfitter.L(key, ...)
    local code = Trainfitter.GetLang()
    local tbl  = Trainfitter.Lang[code] or Trainfitter.Lang.ru
    local raw  = tbl[key] or Trainfitter.Lang.en[key] or key
    if select("#", ...) > 0 then
        local ok, formatted = pcall(string.format, raw, ...)
        if ok then return formatted end
        return raw
    end
    return raw
end
